# Setup
title:               'On the Joy of Problems'
tagline:             ''
description:         'My personal blog about problems I find intriguing. I would love to hear from you! Feel free to reach out through my <a href="https://thasso.xyz/about/">about page</a>.'
url:                 https://thasso.xyz
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Thassilo Schulze
  url:               https://github.com/d4ckard
  email:             thassilo.schulze@posteo.de

social:
  - name: RSS
    url: https://thasso.xyz/atom.xml

  - name: Twitter
    url: https://twitter.com/d4kdd

  - name: GitHub
    url: https://github.com/d4ckard

  - name: LinkedIn
    url: https://www.linkedin.com/in/thassilo-schulze

  - name: Discord
    url: https://discordapp.com/users/566594351522906123


# Gems
plugins:
  - jekyll-paginate

exclude: ["blog-code", "README.md"]
